spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://${HOST_MACHINE}:${POSTGRES_EXPOSED_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
server:
  port: 8182
